config:
  MD013: false
  MD024:
    siblings_only: true
  MD033: false
  MD041: false
  MD029: false

ignores:
  - "**/node_modules/**"
  - "**/.venv/**"
  - "backend/data/**"
  - ".codex/**"
  - "workpackages/**"
