name: Feature request
description: Suggest an enhancement or new feature
title: "[Feature]: "
labels: ["enhancement"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for proposing an improvement!

        Please describe the *problem* first. The best requests explain the pain clearly.
  - type: textarea
    id: problem
    attributes:
      label: Problem / motivation
      description: What problem are you trying to solve? Why does this matter?
      placeholder: "I’m trying to..., but currently..."
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen? Provide details or examples.
      placeholder: "Add/change..., so that..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions or workarounds you've tried.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Links, screenshots, related issues, etc.
    validations:
      required: false
  - type: checkboxes
    id: sanity
    attributes:
      label: Sanity checks
      options:
        - label: I searched existing issues and discussions before opening this.
          required: true
