"""Service layer for backend operations."""

from .events import (
    EventQueryResult,
    EventRecord,
    list_entity_events,
    list_events,
    record_event,
)
from .configurations import (
    ActiveConfigurationNotFoundError,
    ConfigurationMismatchError,
    ConfigurationNotFoundError,
    create_configuration,
    delete_configuration,
    get_active_configuration,
    get_configuration,
    list_configurations,
    resolve_configuration,
    update_configuration,
)
from .jobs import (
    InvalidJobStatusError,
    JobImmutableError,
    JobNotFoundError,
    generate_job_id,
    create_job,
    get_job,
    list_jobs,
    update_job,
)
from .documents import (
    DocumentNotFoundError,
    InvalidDocumentExpirationError,
    store_document,
    list_documents,
    get_document,
    resolve_document_path,
    iter_document_file,
)
from .maintenance_status import (
    get_auto_purge_status,
    record_auto_purge_failure,
    record_auto_purge_success,
)

__all__ = [
    "EventQueryResult",
    "EventRecord",
    "list_entity_events",
    "list_events",
    "record_event",
    "ActiveConfigurationNotFoundError",
    "ConfigurationMismatchError",
    "ConfigurationNotFoundError",
    "create_configuration",
    "delete_configuration",
    "get_active_configuration",
    "get_configuration",
    "list_configurations",
    "resolve_configuration",
    "update_configuration",
    "InvalidJobStatusError",
    "JobImmutableError",
    "JobNotFoundError",
    "generate_job_id",
    "create_job",
    "get_job",
    "list_jobs",
    "update_job",
    "DocumentNotFoundError",
    "InvalidDocumentExpirationError",
    "store_document",
    "list_documents",
    "get_document",
    "resolve_document_path",
    "iter_document_file",
    "get_auto_purge_status",
    "record_auto_purge_failure",
    "record_auto_purge_success",
]
