"""
ADE hook: ``on_workbook_before_save``.

This hook runs once per input file after all tables have been processed and written to
the *output* openpyxl workbook, immediately before the workbook is saved.

Use this hook for workbook-wide presentation and finalization: setting properties and
calculation flags, standardizing sheet UX/print setup, adding summary/helper sheets,
applying workbook-level formatting rules, and optionally hiding or protecting sheets.

Contract
--------
- Called once per output workbook.
- Must return ``None`` (any other return value is an error).

Guidance
--------
- Prefer deterministic, idempotent operations.
- Avoid changing table values here; treat this stage as output polish and UX.
- Keep expensive work in earlier hooks and reuse cached data from ``state`` when possible.
"""


from __future__ import annotations

from collections.abc import Mapping, MutableMapping
from datetime import UTC
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    import openpyxl

    from ade_engine.extensions.registry import Registry
    from ade_engine.infrastructure.observability.logger import RunLogger
    from ade_engine.infrastructure.settings import Settings


def register(registry: Registry) -> None:
    # Default placeholder (no-op).
    registry.register_hook(on_workbook_before_save, hook="on_workbook_before_save", priority=0)

    # Examples (uncomment to enable)
    # registry.register_hook(on_workbook_before_save_example_1_set_properties_and_calc, hook="on_workbook_before_save", priority=10)
    # registry.register_hook(on_workbook_before_save_example_2_standardize_sheet_ux_and_print, hook="on_workbook_before_save", priority=20)
    # registry.register_hook(on_workbook_before_save_example_3_namedstyle_headers, hook="on_workbook_before_save", priority=30)
    # registry.register_hook(on_workbook_before_save_example_4_autosize_columns_and_number_formats, hook="on_workbook_before_save", priority=40)
    # registry.register_hook(on_workbook_before_save_example_5_add_run_summary_sheet_with_links_and_chart, hook="on_workbook_before_save", priority=50)
    # registry.register_hook(on_workbook_before_save_example_6_convert_ranges_to_excel_tables, hook="on_workbook_before_save", priority=60)
    # registry.register_hook(on_workbook_before_save_example_7_apply_conditional_formatting, hook="on_workbook_before_save", priority=70)
    # registry.register_hook(on_workbook_before_save_example_8_add_data_validation_dropdowns, hook="on_workbook_before_save", priority=80)
    # registry.register_hook(on_workbook_before_save_example_9_hide_helper_sheets_and_set_active, hook="on_workbook_before_save", priority=90)
    # registry.register_hook(on_workbook_before_save_example_10_protect_sheets, hook="on_workbook_before_save", priority=100)


# -----------------------------------------------------------------------------
# Default hook (minimal + safe)
# -----------------------------------------------------------------------------


def on_workbook_before_save(
    *,
    workbook: openpyxl.Workbook,  # Output workbook (openpyxl Workbook)
    input_file_name: str,  # Input filename (basename)
    settings: Settings,  # Engine Settings
    metadata: Mapping[str, Any],  # Run metadata (filenames, etc.)
    state: MutableMapping[str, Any],  # Mutable dict shared across the run
    logger: RunLogger,  # RunLogger (structured events + text logs)
) -> None:  # noqa: ARG001
    """Default implementation is a placeholder (no-op)."""
    return None


# -----------------------------------------------------------------------------
# Example 1: workbook properties + force formula recalculation
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_1_set_properties_and_calc(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 1: Set workbook properties and ask Excel to recalc formulas on open.

    Useful when:
      - You generate files for humans (title/author helps searchability).
      - You write formulas (openpyxl does NOT compute formulas; Excel will).
    """
    from datetime import datetime

    # Core properties (Excel: File -> Info)
    props = workbook.properties
    props.creator = "Automatic Data Extractor (ADE)"
    props.lastModifiedBy = "ADE"

    now_utc_naive = datetime.now(UTC).replace(tzinfo=None)
    props.created = now_utc_naive
    props.modified = now_utc_naive

    input_name = (
        input_file_name or metadata.get("input_file_name") or metadata.get("input_file") or ""
    )
    if input_name:
        props.title = f"Normalized - {input_name}"
        props.subject = input_name

    out = metadata.get("output_file") or ""
    if out:
        props.description = f"Generated by ADE. Output: {out}"

    # Ask Excel to recalculate on open (important if you add formulas).
    try:
        workbook.calculation.fullCalcOnLoad = True
    except Exception:
        # Some workbook objects/openpyxl versions may not expose this—safe to ignore.
        pass

    # Choose which sheet opens by default (0 = first sheet).
    workbook.active = 0

    if logger:
        logger.info("Example 1: set workbook properties + fullCalcOnLoad")


# -----------------------------------------------------------------------------
# Example 2: standard sheet UX + print setup everywhere
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_2_standardize_sheet_ux_and_print(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 2: Apply consistent worksheet UX and print settings.

    Demonstrates:
      - freeze panes
      - gridlines off
      - auto-filter on the used range
      - print title rows + landscape + fit-to-width
    """
    for ws in getattr(workbook, "worksheets", []) or []:
        # Skip truly empty sheets
        if ws.max_row == 1 and ws.max_column == 1 and ws["A1"].value in (None, ""):
            continue

        # Freeze top row (header stays visible)
        if ws.max_row >= 2:
            ws.freeze_panes = "A2"

        # Cleaner look for reports
        ws.sheet_view.showGridLines = False

        # Filter dropdowns in header row (only makes sense if you have header + rows)
        if ws.max_row >= 2 and ws.max_column >= 1:
            ws.auto_filter.ref = ws.dimensions

        # Print defaults
        try:
            ws.print_title_rows = "1:1"
            ws.page_setup.orientation = "landscape"
            ws.page_setup.fitToWidth = 1
            ws.page_setup.fitToHeight = 0
        except Exception:
            pass

    if logger:
        logger.info("Example 2: standardized worksheet UX + print setup")


# -----------------------------------------------------------------------------
# Example 3: NamedStyle + header row styling (fast and reusable)
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_3_namedstyle_headers(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 3: Create a NamedStyle and apply it to header rows.

    Why NamedStyle?
      - Consistent styles across workbook
      - Easy to apply (cell.style = "NAME")
      - Avoids copy/pasting style objects everywhere
    """
    from openpyxl.styles import Alignment, Border, Font, NamedStyle, PatternFill, Side

    # Create (or reuse) a named header style
    thin = Side(style="thin", color="D9D9D9")
    header_style = NamedStyle(
        name="ADE_Header",
        font=Font(bold=True, color="1F2937"),
        alignment=Alignment(vertical="top", wrap_text=True),
        fill=PatternFill("solid", fgColor="F3F4F6"),
        border=Border(bottom=thin),
    )

    existing = set()
    for item in getattr(workbook, "named_styles", []) or []:
        if isinstance(item, str):
            existing.add(item)
        else:
            existing.add(getattr(item, "name", ""))

    if header_style.name not in existing:
        workbook.add_named_style(header_style)

    for ws in getattr(workbook, "worksheets", []) or []:
        if ws.max_row < 1 or ws.max_column < 1:
            continue
        for cell in ws[1]:
            cell.style = header_style.name
        try:
            ws.row_dimensions[1].height = 20
        except Exception:
            pass

    if logger:
        logger.info("Example 3: applied NamedStyle '%s' to header rows", header_style.name)


# -----------------------------------------------------------------------------
# Example 4: autosize columns (sampled) + basic number formats by header
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_4_autosize_columns_and_number_formats(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 4: Auto-size columns (fast sampling) and set number formats by header name.

    Demonstrates:
      - values_only iteration for speed
      - width estimation
      - applying number formats by header heuristics (common in exports)
    """
    from openpyxl.styles import numbers
    from openpyxl.utils import get_column_letter

    SAMPLE_ROWS = 250
    MIN_W = 10
    MAX_W = 60

    # Simple header->format mapping (customize to your outputs)
    # Tip: prefer stable header names in your pipeline if you want reliable formatting.
    HEADER_FORMATS = {
        "date": numbers.FORMAT_DATE_YYYYMMDD2,
        "created_at": numbers.FORMAT_DATE_DATETIME,
        "updated_at": numbers.FORMAT_DATE_DATETIME,
        "amount": numbers.FORMAT_CURRENCY_USD_SIMPLE,
        "total": numbers.FORMAT_NUMBER_00,
        "percent": "0.00%",
    }

    def guess_format(header: str | None) -> str | None:
        if not header:
            return None
        key = str(header).strip().lower()
        return HEADER_FORMATS.get(key)

    for ws in getattr(workbook, "worksheets", []) or []:
        if ws.max_row < 1 or ws.max_column < 1:
            continue

        # --- Auto-size widths (sampled) ---
        max_row = min(ws.max_row, max(1, SAMPLE_ROWS))
        widths = [0] * ws.max_column

        for row in ws.iter_rows(
            min_row=1,
            max_row=max_row,
            min_col=1,
            max_col=ws.max_column,
            values_only=True,
        ):
            for i, v in enumerate(row):
                if v is None:
                    continue
                s = str(v)
                if "\n" in s:
                    s = max(s.splitlines(), key=len)
                widths[i] = max(widths[i], len(s))

        for col_idx, max_len in enumerate(widths, start=1):
            ws.column_dimensions[get_column_letter(col_idx)].width = float(
                min(max(max_len + 2, MIN_W), MAX_W)
            )

        # --- Apply number formats by header (bounded) ---
        # Performance note: formatting every cell can be slow on giant sheets.
        # Keep it to columns that match, and optionally cap rows.
        header_row = [c.value for c in ws[1]]
        for col_idx, header_val in enumerate(header_row, start=1):
            fmt = guess_format(header_val)
            if not fmt:
                continue

            # Apply format to the data cells only (skip header)
            max_format_row = min(ws.max_row, 20_000)
            for cell in ws.iter_cols(
                min_col=col_idx, max_col=col_idx, min_row=2, max_row=max_format_row
            ):
                for c in cell:
                    c.number_format = fmt

    if logger:
        logger.info("Example 4: autosized columns + applied basic number formats")


# -----------------------------------------------------------------------------
# Example 5: add a Run Summary sheet (links + formulas + chart)
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_5_add_run_summary_sheet_with_links_and_chart(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 5: Create a “Run Summary” sheet at the front of the workbook.

    Demonstrates:
      - creating/replacing a sheet
      - internal hyperlinks to worksheets
      - formulas (Excel computes on open)
      - a simple chart
    """
    from datetime import datetime

    from openpyxl.chart import BarChart, Reference
    from openpyxl.styles import Alignment, Font

    def safe_sheet_ref(title: str) -> str:
        # Quote sheet names with spaces/specials; escape single quotes by doubling.
        if any(ch in title for ch in (" ", "-", "!", "'", "(", ")", ",")):
            return "'" + title.replace("'", "''") + "'"
        return title

    # Replace existing sheet if present
    title = "Run Summary"
    if title in getattr(workbook, "sheetnames", []):
        workbook.remove(workbook[title])
    ws = workbook.create_sheet(title=title, index=0)

    # Header
    ws["A1"] = "Run Summary"
    ws["A1"].font = Font(size=16, bold=True)
    ws["A1"].alignment = Alignment(vertical="center")
    ws.merge_cells("A1:D1")
    ws.row_dimensions[1].height = 24

    # Metadata
    ws["A3"] = "input_file"
    ws["B3"] = metadata.get("input_file") or input_file_name or ""
    ws["A4"] = "output_file"
    ws["B4"] = metadata.get("output_file") or ""
    ws["A5"] = "generated_at_utc"
    ws["B5"] = datetime.now(UTC).replace(tzinfo=None).isoformat(sep=" ", timespec="seconds")

    # Sheet stats table
    ws.append([])
    header_row_idx = ws.max_row + 1
    ws.append(["sheet", "rows", "columns", "notes"])

    data_sheets = [s for s in (getattr(workbook, "worksheets", []) or []) if s.title != ws.title]

    for s in data_sheets:
        if s.max_row == 1 and s.max_column == 1 and s["A1"].value in (None, ""):
            rows = 0
            cols = 0
        else:
            rows = max(int(getattr(s, "max_row", 0) or 0) - 1, 0)
            cols = int(getattr(s, "max_column", 0) or 0)

        r = ws.max_row + 1
        link = ws.cell(row=r, column=1, value=s.title)
        link.hyperlink = f"#{safe_sheet_ref(s.title)}!A1"
        link.style = "Hyperlink"
        ws.cell(row=r, column=2, value=rows)
        ws.cell(row=r, column=3, value=cols)
        ws.cell(row=r, column=4, value="")

    end_row = ws.max_row
    ws.freeze_panes = f"A{header_row_idx + 1}"
    ws.sheet_view.showGridLines = False

    # Totals (Excel computes on open)
    ws.cell(row=end_row + 2, column=1, value="TOTAL")
    ws.cell(row=end_row + 2, column=2, value=f"=SUM(B{header_row_idx + 1}:B{end_row})")
    ws.cell(row=end_row + 2, column=3, value=f"=MAX(C{header_row_idx + 1}:C{end_row})")

    # Chart: rows per sheet
    if end_row >= header_row_idx + 1:
        chart = BarChart()
        chart.title = "Rows per sheet"
        chart.y_axis.title = "rows"
        chart.x_axis.title = "sheet"
        data = Reference(ws, min_col=2, min_row=header_row_idx, max_row=end_row)  # includes header
        cats = Reference(ws, min_col=1, min_row=header_row_idx + 1, max_row=end_row)
        chart.add_data(data, titles_from_data=True)
        chart.set_categories(cats)
        chart.height = 7
        chart.width = 16
        ws.add_chart(chart, "F3")

    # Make summary the active sheet by default
    workbook.active = 0

    if logger:
        logger.info("Example 5: wrote Run Summary sheet (sheets=%d)", len(data_sheets))


# -----------------------------------------------------------------------------
# Example 6: convert each used range into an Excel Table (structured refs)
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_6_convert_ranges_to_excel_tables(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 6: Convert each sheet's used range to an Excel Table.

    Demonstrates:
      - openpyxl Table objects
      - table styling (banded rows)
      - ensuring header uniqueness (Excel requires unique header names)
    """
    import re

    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.table import Table, TableStyleInfo

    def sanitize_table_name(name: str) -> str:
        cleaned = re.sub(r"[^A-Za-z0-9_]", "_", name or "").strip("_")
        if not cleaned:
            cleaned = "Table"
        if cleaned[0].isdigit():
            cleaned = f"T_{cleaned}"
        return cleaned[:255]

    def ensure_unique_headers(ws) -> None:
        headers = []
        for idx, cell in enumerate(ws[1], start=1):
            raw = cell.value
            txt = str(raw).strip().replace("\n", " ") if raw not in (None, "") else f"column_{idx}"
            headers.append(txt)

        seen: dict[str, int] = {}
        fixed = []
        changed = False
        for h in headers:
            if h in seen:
                seen[h] += 1
                fixed.append(f"{h}_{seen[h]}")
                changed = True
            else:
                seen[h] = 1
                fixed.append(h)
        if changed:
            for cell, val in zip(ws[1], fixed, strict=False):
                cell.value = val

    existing_names: set[str] = set()
    for ws in getattr(workbook, "worksheets", []) or []:
        for t in getattr(ws, "tables", {}).values():
            n = getattr(t, "displayName", None)
            if n:
                existing_names.add(n)

    created = 0
    for ws in getattr(workbook, "worksheets", []) or []:
        if ws.max_row < 2 or ws.max_column < 1:
            continue
        if getattr(ws, "tables", None) and len(ws.tables) > 0:
            continue

        ensure_unique_headers(ws)

        ref = f"A1:{get_column_letter(ws.max_column)}{ws.max_row}"
        base = sanitize_table_name(f"T_{ws.title}")
        name = base
        i = 2
        while name in existing_names:
            name = f"{base}_{i}"
            i += 1

        table_obj = Table(displayName=name, ref=ref)
        table_obj.tableStyleInfo = TableStyleInfo(
            name="TableStyleMedium9",
            showFirstColumn=False,
            showLastColumn=False,
            showRowStripes=True,
            showColumnStripes=False,
        )

        try:
            ws.add_table(table_obj)
            existing_names.add(name)
            created += 1
        except Exception as e:
            if logger:
                logger.info("Example 6: skipped table on '%s' (%s)", ws.title, e)

    if logger:
        logger.info("Example 6: created Excel Tables on %d sheet(s)", created)


# -----------------------------------------------------------------------------
# Example 7: conditional formatting (blanks, negatives, and a color scale)
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_7_apply_conditional_formatting(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 7: Apply conditional formatting to each sheet's used range.

    Demonstrates:
      - FormulaRule (blanks)
      - CellIsRule (negative numbers)
      - ColorScaleRule (heatmap-ish for a numeric column)
    """
    from openpyxl.formatting.rule import CellIsRule, ColorScaleRule, FormulaRule
    from openpyxl.styles import PatternFill
    from openpyxl.utils import get_column_letter

    fill_blank = PatternFill("solid", fgColor="FFF7D6")  # soft yellow
    fill_negative = PatternFill("solid", fgColor="FADBD8")  # soft red

    applied = 0
    for ws in getattr(workbook, "worksheets", []) or []:
        if ws.max_row < 2 or ws.max_column < 1:
            continue

        last_col = get_column_letter(ws.max_column)
        data_range = f"A2:{last_col}{ws.max_row}"

        # Highlight blank/whitespace cells (Excel evaluates per-cell)
        ws.conditional_formatting.add(
            data_range,
            FormulaRule(formula=["LEN(TRIM(A2))=0"], fill=fill_blank),
        )

        # Highlight negative numbers
        ws.conditional_formatting.add(
            data_range,
            CellIsRule(operator="lessThan", formula=["0"], fill=fill_negative),
        )

        # Add a color scale to column B (if present) as a simple visual.
        # Adjust to your numeric column(s).
        if ws.max_column >= 2 and ws.max_row >= 3:
            col_b = f"B2:B{ws.max_row}"
            ws.conditional_formatting.add(
                col_b,
                ColorScaleRule(
                    start_type="min",
                    start_color="FEE2E2",  # light red
                    mid_type="percentile",
                    mid_value=50,
                    mid_color="FEF9C3",  # light yellow
                    end_type="max",
                    end_color="DCFCE7",  # light green
                ),
            )

        applied += 1

    if logger:
        logger.info("Example 7: applied conditional formatting on %d sheet(s)", applied)


# -----------------------------------------------------------------------------
# Example 8: data validation dropdowns (simple workflow columns)
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_8_add_data_validation_dropdowns(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 8: Add a dropdown (DataValidation) to a 'status' column if present.

    Demonstrates:
      - scanning header row for a specific column name
      - adding a list validation to a whole column range
    """
    from openpyxl.utils import get_column_letter
    from openpyxl.worksheet.datavalidation import DataValidation

    STATUS_VALUES = "todo,in_review,blocked,done"
    TARGET_HEADERS = {"status", "review_status"}

    updated = 0
    for ws in getattr(workbook, "worksheets", []) or []:
        if ws.max_row < 2 or ws.max_column < 1:
            continue

        headers = [str(c.value).strip().lower() if c.value not in (None, "") else "" for c in ws[1]]
        try:
            col_idx = next(i + 1 for i, h in enumerate(headers) if h in TARGET_HEADERS)
        except StopIteration:
            continue

        col_letter = get_column_letter(col_idx)
        dv = DataValidation(type="list", formula1=f'"{STATUS_VALUES}"', allow_blank=True)
        ws.add_data_validation(dv)

        # Apply to entire used range in that column (excluding header)
        dv.add(f"{col_letter}2:{col_letter}{ws.max_row}")
        updated += 1

    if logger:
        logger.info("Example 8: added status dropdown validation on %d sheet(s)", updated)


# -----------------------------------------------------------------------------
# Example 9: hide helper sheets (by naming convention) + set active sheet
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_9_hide_helper_sheets_and_set_active(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 9: Hide helper sheets and choose a default active sheet.

    Common convention:
      - helper sheets start with "_" or "tmp"
    """
    hidden = 0
    for ws in getattr(workbook, "worksheets", []) or []:
        if ws.title.startswith("_") or ws.title.lower().startswith("tmp"):
            try:
                ws.sheet_state = "hidden"
                hidden += 1
            except Exception:
                pass

    # Prefer "Run Summary" if present, else first visible sheet.
    if "Run Summary" in getattr(workbook, "sheetnames", []):
        workbook.active = workbook.sheetnames.index("Run Summary")
    else:
        workbook.active = 0

    if logger:
        logger.info(
            "Example 9: hidden helper sheets=%d; set active sheet index=%d", hidden, workbook.active
        )


# -----------------------------------------------------------------------------
# Example 10: protect sheets from accidental edits (not strong security)
# -----------------------------------------------------------------------------


def on_workbook_before_save_example_10_protect_sheets(
    *,
    workbook: openpyxl.Workbook,
    input_file_name: str,
    settings: Settings,
    metadata: Mapping[str, Any],
    state: MutableMapping[str, Any],
    logger: RunLogger,
) -> None:  # noqa: ARG001
    """Example 10: Protect worksheets from accidental edits.

    IMPORTANT:
      - Excel sheet protection is not strong security.
      - Use it to reduce accidental changes, not for secrets.
    """
    PASSWORD = "change-me"  # If you use this, set it via env/settings instead of hardcoding.
    protected = 0

    for ws in getattr(workbook, "worksheets", []) or []:
        # Skip empty sheets
        if ws.max_row == 1 and ws.max_column == 1 and ws["A1"].value in (None, ""):
            continue
        try:
            ws.protection.sheet = True
            ws.protection.set_password(PASSWORD)
            protected += 1
        except Exception:
            pass

    if logger:
        logger.info("Example 10: protected sheets=%d", protected)
