"""Filesystem helpers for job execution artifacts."""

import json
import shutil
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from zipfile import ZIP_DEFLATED, ZipFile

from backend.app.shared.core.config import Settings
from backend.app.shared.core.time import utc_now


@dataclass(slots=True)
class JobStoragePaths:
    job_dir: Path
    config_dir: Path
    artifact_path: Path
    output_path: Path
    logs_path: Path


class JobsStorage:
    """Manage on-disk storage for job runs."""

    def __init__(self, settings: Settings) -> None:
        self._base_dir = Path(settings.storage_data_dir) / "jobs"
        self._base_dir.mkdir(parents=True, exist_ok=True)

    def prepare(self, job_id: str) -> JobStoragePaths:
        job_dir = self._base_dir / job_id
        if job_dir.exists():
            shutil.rmtree(job_dir)
        config_dir = job_dir / "config"
        artifact_path = job_dir / "artifact.json"
        output_path = job_dir / "normalized.xlsx"
        logs_path = job_dir / "logs.txt"
        config_dir.mkdir(parents=True, exist_ok=True)
        logs_path.touch(exist_ok=True)
        return JobStoragePaths(
            job_dir=job_dir,
            config_dir=config_dir,
            artifact_path=artifact_path,
            output_path=output_path,
            logs_path=logs_path,
        )

    def copy_config(self, source: Path, destination: Path) -> None:
        if destination.exists():
            shutil.rmtree(destination)
        shutil.copytree(source, destination)

    def write_artifact(self, path: Path, payload: dict[str, Any]) -> None:
        path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    def write_workbook(self, path: Path, target_fields: list[str]) -> None:
        try:
            from openpyxl import Workbook  # type: ignore import-not-found
        except ModuleNotFoundError:  # pragma: no cover - fallback path when dependency missing
            self._write_minimal_workbook(path, target_fields)
            return

        workbook = Workbook()
        sheet = workbook.active
        sheet.title = "Normalized"
        sheet.append(["Generated By", "Fields"])
        sheet.append([
            "ADE",
            ", ".join(sorted(target_fields)),
        ])
        workbook.save(path)

    def _write_minimal_workbook(self, path: Path, target_fields: list[str]) -> None:
        fields = ", ".join(sorted(target_fields))
        timestamp = utc_now().replace(microsecond=0).isoformat()

        sheet_rows = [
            [("A1", "Generated By"), ("B1", "Fields")],
            [("A2", "ADE"), ("B2", fields)],
        ]
        row_fragments: list[str] = []
        for index, cells in enumerate(sheet_rows, start=1):
            cells_xml = "".join(
                f'<c r="{cell}" t="inlineStr"><is><t>{self._escape(value)}</t></is></c>'
                for cell, value in cells
            )
            row_fragments.append(f'        <row r="{index}">{cells_xml}</row>')
        sheet_xml = (
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<worksheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\">\n"
            "    <dimension ref=\"A1:B2\"/>\n"
            "    <sheetData>\n"
            f"{'\\n'.join(row_fragments)}\n"
            "    </sheetData>\n"
            "</worksheet>"
        )

        content_types = (
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<Types xmlns=\"http://schemas.openxmlformats.org/package/2006/content-types\">\n"
            "    <Default Extension=\"rels\" ContentType=\"application/vnd.openxmlformats-package.relationships+xml\"/>\n"
            "    <Default Extension=\"xml\" ContentType=\"application/xml\"/>\n"
            "    <Override PartName=\"/xl/workbook.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml\"/>\n"
            "    <Override PartName=\"/xl/worksheets/sheet1.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml\"/>\n"
            "    <Override PartName=\"/xl/styles.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.spreadsheetml.styles+xml\"/>\n"
            "    <Override PartName=\"/docProps/core.xml\" ContentType=\"application/vnd.openxmlformats-package.core-properties+xml\"/>\n"
            "    <Override PartName=\"/docProps/app.xml\" ContentType=\"application/vnd.openxmlformats-officedocument.extended-properties+xml\"/>\n"
            "</Types>"
        )

        rels_xml = (
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">\n"
            "    <Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument\" Target=\"xl/workbook.xml\"/>\n"
            "    <Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties\" Target=\"docProps/core.xml\"/>\n"
            "    <Relationship Id=\"rId3\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties\" Target=\"docProps/app.xml\"/>\n"
            "</Relationships>"
        )

        workbook_xml = (
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<workbook xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\" "
            "xmlns:r=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships\">\n"
            "    <sheets>\n"
            "        <sheet name=\"Normalized\" sheetId=\"1\" r:id=\"rId1\"/>\n"
            "    </sheets>\n"
            "</workbook>"
        )

        workbook_rels = (
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<Relationships xmlns=\"http://schemas.openxmlformats.org/package/2006/relationships\">\n"
            "    <Relationship Id=\"rId1\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet\" Target=\"worksheets/sheet1.xml\"/>\n"
            "    <Relationship Id=\"rId2\" Type=\"http://schemas.openxmlformats.org/officeDocument/2006/relationships/styles\" Target=\"styles.xml\"/>\n"
            "</Relationships>"
        )

        styles_xml = (
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<styleSheet xmlns=\"http://schemas.openxmlformats.org/spreadsheetml/2006/main\">\n"
            "    <fonts count=\"1\"><font/></fonts>\n"
            "    <fills count=\"1\"><fill/></fills>\n"
            "    <borders count=\"1\"><border/></borders>\n"
            "    <cellStyleXfs count=\"1\"><xf/></cellStyleXfs>\n"
            "    <cellXfs count=\"1\"><xf xfId=\"0\"/></cellXfs>\n"
            "</styleSheet>"
        )

        core_xml = (
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<cp:coreProperties xmlns:cp=\"http://schemas.openxmlformats.org/package/2006/metadata/core-properties\" "
            "xmlns:dc=\"http://purl.org/dc/elements/1.1/\" xmlns:dcterms=\"http://purl.org/dc/terms/\" "
            "xmlns:dcmitype=\"http://purl.org/dc/dcmitype/\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\n"
            "    <dc:title>Normalized</dc:title>\n"
            "    <dc:creator>ADE</dc:creator>\n"
            "    <cp:lastModifiedBy>ADE</cp:lastModifiedBy>\n"
            f"    <dcterms:created xsi:type=\"dcterms:W3CDTF\">{timestamp}</dcterms:created>\n"
            f"    <dcterms:modified xsi:type=\"dcterms:W3CDTF\">{timestamp}</dcterms:modified>\n"
            "</cp:coreProperties>"
        )

        app_xml = (
            "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"
            "<Properties xmlns=\"http://schemas.openxmlformats.org/officeDocument/2006/extended-properties\" "
            "xmlns:vt=\"http://schemas.openxmlformats.org/officeDocument/2006/docPropsVTypes\">\n"
            "    <Application>ADE</Application>\n"
            "</Properties>"
        )

        with ZipFile(path, "w", compression=ZIP_DEFLATED) as archive:
            archive.writestr("[Content_Types].xml", content_types)
            archive.writestr("_rels/.rels", rels_xml)
            archive.writestr("docProps/core.xml", core_xml)
            archive.writestr("docProps/app.xml", app_xml)
            archive.writestr("xl/workbook.xml", workbook_xml)
            archive.writestr("xl/_rels/workbook.xml.rels", workbook_rels)
            archive.writestr("xl/styles.xml", styles_xml)
            archive.writestr("xl/worksheets/sheet1.xml", sheet_xml)

    @staticmethod
    def _escape(value: str) -> str:
        return (
            value.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace("\"", "&quot;")
            .replace("'", "&apos;")
        )


__all__ = ["JobsStorage", "JobStoragePaths"]
