export const adminKeys = {
  all: () => ["admin"] as const,
  users: () => [...adminKeys.all(), "users"] as const,
  usersList: (params: Record<string, unknown> = {}) => [...adminKeys.users(), "list", params] as const,
  user: (userId: string) => [...adminKeys.users(), "detail", userId] as const,
  roles: () => [...adminKeys.all(), "roles"] as const,
  rolesList: (params: Record<string, unknown> = {}) => [...adminKeys.roles(), "list", params] as const,
  permissions: (scope: "global" | "workspace") => [...adminKeys.roles(), "permissions", scope] as const,
  userRoles: (userId: string) => [...adminKeys.roles(), "user-roles", userId] as const,
  apiKeys: () => [...adminKeys.all(), "api-keys"] as const,
  apiKeysList: (params: Record<string, unknown> = {}) => [...adminKeys.apiKeys(), "list", params] as const,
  userApiKeys: (userId: string) => [...adminKeys.apiKeys(), "user", userId] as const,
  sso: () => [...adminKeys.all(), "sso"] as const,
  ssoProviders: () => [...adminKeys.sso(), "providers"] as const,
  scim: () => [...adminKeys.all(), "scim"] as const,
  scimTokens: () => [...adminKeys.scim(), "tokens"] as const,
  settings: () => [...adminKeys.all(), "settings"] as const,
};
